# Generated by Django 4.2.27 on 2026-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En progreso'), ('closed', 'Cerrado'), ('expired', 'Expirado'), ('pending', 'Pendiente'), ('resolved', 'Resuelto')], default='open', max_length=20),
        ),
    ]
